[2017-02-14 19:07:43,308] pwnage101/INFO/helpers.settings: using settings file: /home/pwnage101/edx-load-tests/settings_files/lms.yml
[2017-02-14 19:07:43,312] pwnage101/INFO/helpers.settings: no secrets were specified in the settings file
[2017-02-14 19:07:43,312] pwnage101/INFO/helpers.settings: loaded the following public settings:
{'LOCUST_MAX_WAIT': 1000,
 'LOCUST_MIN_WAIT': 300,
 'LOCUST_TASK_SET': 'LmsTest',
 'MODULE_RENDER_MODIFIER': 1,
 'PROCTORED_EXAM_MODIFIER': 1,
 'courses': {'course-v1:Fx+LT001+2015_T3': {'course_data': 'demo_course_feanil',
                                            'ratio': 1},
             'edX/DemoX/Demo_Course': {'course_data': 'demo_course',
                                       'ratio': 1}}}
[2017-02-14 19:07:43,313] pwnage101/INFO/locust.main: Starting Locust 0.7.5
[2017-02-14 19:07:43,313] pwnage101/INFO/locust.runners: Hatching and swarming 525 clients at the rate 25 clients/s...
[2017-02-14 19:07:46,883] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:48,013] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:49,683] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:50,143] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:51,290] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:52,242] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:53,473] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:55,183] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:55,680] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:07:56,226] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:08:00,567] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:08:00,927] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:08:07,296] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:08:07,697] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:08:13,008] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:08:13,594] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:08:14,084] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-02-14 19:08:14,215] pwnage101/INFO/locust.runners: All locusts hatched: LmsLocust: 525
[2017-02-14 19:08:14,215] pwnage101/INFO/locust.runners: Resetting stats

[2017-02-14 19:08:33,510] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-02-14 19:09:12,070] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:09:19,529] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:09:29,183] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 273, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 149, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:09:52,411] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 273, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 149, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:09:58,959] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:10:32,154] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-02-14 19:11:14,251] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 273, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 149, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:11:40,068] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 273, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 149, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:13:15,722] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 273, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 149, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:13:23,580] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 273, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 149, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:15:05,713] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 273, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 149, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:15:55,684] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-02-14 19:16:08,014] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 273, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 149, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:16:10,766] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:16:23,389] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:16:24,326] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:17:08,765] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-02-14 19:17:28,993] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 230, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 115, in create_thread
    thread_id = response.json()['id']
KeyError: 'id'
[2017-02-14 19:17:43,047] pwnage101/INFO/locust.main: Got SIGTERM signal
[2017-02-14 19:17:43,047] pwnage101/INFO/locust.main: Shutting down (exit code 0), bye.
