[2017-01-18 21:51:37,145] pwnage101/INFO/helpers.settings: using settings file: /home/pwnage101/edx-load-tests/settings_files/lms.yml
[2017-01-18 21:51:37,148] pwnage101/INFO/helpers.settings: no secrets were specified in the settings file
[2017-01-18 21:51:37,148] pwnage101/INFO/helpers.settings: loaded the following public settings:
{'COURSE_DATA': 'demo_course',
 'COURSE_ID': 'course-v1:Fx+LT001+2015_T3',
 'LOCUST_MAX_WAIT': 1000,
 'LOCUST_MIN_WAIT': 300,
 'LOCUST_TASK_SET': 'LmsTest',
 'MODULE_RENDER_MODIFIER': 1,
 'PROCTORED_EXAM_MODIFIER': 1}
[2017-01-18 21:51:37,149] pwnage101/INFO/locust.main: Starting Locust 0.7.5
[2017-01-18 21:51:37,149] pwnage101/INFO/locust.runners: Hatching and swarming 175 clients at the rate 25 clients/s...
[2017-01-18 21:51:38,327] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 21:51:39,503] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 21:51:42,077] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 21:51:43,543] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 21:51:44,266] pwnage101/ERROR/stderr: Traceback (most recent call last):
[2017-01-18 21:51:44,266] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
[2017-01-18 21:51:44,266] pwnage101/ERROR/stderr: result = self._run(*self.args, **self.kwargs)
[2017-01-18 21:51:44,266] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/runners.py", line 113, in start_locust
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: locust().run()
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 102, in run
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: self.task_set(self).run()
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: self.execute_next_task()
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: self.execute_task(task["callable"], *task["args"], **task["kwargs"])
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: task(self).run(*args, **kwargs)
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: self.execute_next_task()
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: self.execute_task(task["callable"], *task["args"], **task["kwargs"])
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: task(self, *args, **kwargs)
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/loadtests/lms/courseware_views.py", line 38, in mktg_course_about
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: self.get('mktg-about', name='courseware:mktg_course_about')
[2017-01-18 21:51:44,267] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/loadtests/lms/base.py", line 123, in get
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: return self._request('get', *args, **kwargs)
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/loadtests/lms/base.py", line 114, in _request
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: return getattr(self.client, method)(path, *args, **kwargs)
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: return self.request('GET', url, **kwargs)
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/clients.py", line 113, in request
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: response = self._send_request_safe_mode(method, url, **kwargs)
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/clients.py", line 157, in _send_request_safe_mode
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: return requests.Session.request(self, method, url, **kwargs)
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: KeyboardInterrupt
[2017-01-18 21:51:44,268] pwnage101/ERROR/stderr: <Greenlet at 0x7f8c7c16fcd0: start_locust(<class 'lms.locustfile.LmsLocust'>)> failed with KeyboardInterrupt
[2017-01-18 21:51:44,268] pwnage101/INFO/locust.main: Shutting down (exit code 0), bye.
[2017-01-18 21:51:53,813] pwnage101/INFO/helpers.settings: using settings file: /home/pwnage101/edx-load-tests/settings_files/lms.yml
[2017-01-18 21:51:53,816] pwnage101/INFO/helpers.settings: no secrets were specified in the settings file
[2017-01-18 21:51:53,816] pwnage101/INFO/helpers.settings: loaded the following public settings:
{'COURSE_DATA': 'demo_course',
 'COURSE_ID': 'course-v1:Fx+LT001+2015_T3',
 'LOCUST_MAX_WAIT': 1000,
 'LOCUST_MIN_WAIT': 300,
 'LOCUST_TASK_SET': 'LmsTest',
 'MODULE_RENDER_MODIFIER': 1,
 'PROCTORED_EXAM_MODIFIER': 1}
[2017-01-18 21:51:53,816] pwnage101/INFO/locust.main: Starting Locust 0.7.5
[2017-01-18 21:51:53,816] pwnage101/INFO/locust.runners: Hatching and swarming 175 clients at the rate 25 clients/s...
[2017-01-18 21:51:55,190] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 21:51:59,087] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 21:52:01,152] pwnage101/INFO/locust.runners: All locusts hatched: LmsLocust: 175
[2017-01-18 21:52:01,152] pwnage101/INFO/locust.runners: Resetting stats

[2017-01-18 21:52:01,277] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:01:53,542] pwnage101/INFO/locust.main: Got SIGTERM signal
[2017-01-18 22:01:53,542] pwnage101/INFO/locust.main: Shutting down (exit code 0), bye.
