[2017-01-18 22:53:54,241] pwnage101/INFO/helpers.settings: using settings file: /home/pwnage101/edx-load-tests/settings_files/lms.yml
[2017-01-18 22:53:54,243] pwnage101/INFO/helpers.settings: no secrets were specified in the settings file
[2017-01-18 22:53:54,244] pwnage101/INFO/helpers.settings: loaded the following public settings:
{'COURSE_DATA': 'demo_course',
 'COURSE_ID': 'course-v1:Fx+LT001+2015_T3',
 'LOCUST_MAX_WAIT': 1000,
 'LOCUST_MIN_WAIT': 300,
 'LOCUST_TASK_SET': 'LmsTest',
 'MODULE_RENDER_MODIFIER': 1,
 'PROCTORED_EXAM_MODIFIER': 1}
[2017-01-18 22:53:54,244] pwnage101/INFO/locust.main: Starting Locust 0.7.5
[2017-01-18 22:53:54,244] pwnage101/INFO/locust.runners: Hatching and swarming 438 clients at the rate 25 clients/s...
[2017-01-18 22:53:55,304] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:53:57,061] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:53:57,556] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:53:59,613] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:54:01,071] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:54:04,365] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:54:05,084] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:54:06,559] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:54:07,180] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:54:18,009] pwnage101/INFO/locust.runners: All locusts hatched: LmsLocust: 438
[2017-01-18 22:54:18,009] pwnage101/INFO/locust.runners: Resetting stats

[2017-01-18 22:54:18,251] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:54:19,421] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 22:54:21,572] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-18 23:00:11,417] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:00:17,772] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:00:34,355] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:01:16,545] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:01:24,282] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:01:27,537] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:01:28,129] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:01:34,181] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:01:47,410] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:01:53,212] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:02:07,889] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:02:11,814] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:02:25,549] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:02:29,046] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:02:29,080] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:02:32,986] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:02:34,424] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:02:51,999] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:07,286] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:14,146] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:16,416] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:25,393] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:32,025] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:37,229] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:44,470] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:52,476] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 224, in create_thread
    thread = super(ForumsTasks, self).create_thread(self.random_topic_id(), name='forums:create_thread')
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 109, in create_thread
    thread_id = response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 9 column 1 (char 8)
[2017-01-18 23:03:53,976] pwnage101/INFO/locust.main: Got SIGTERM signal
[2017-01-18 23:03:53,976] pwnage101/INFO/locust.main: Shutting down (exit code 0), bye.
