[2017-01-19 21:00:35,377] pwnage101/INFO/helpers.settings: using settings file: /home/pwnage101/edx-load-tests/settings_files/lms.yml
[2017-01-19 21:00:35,379] pwnage101/INFO/helpers.settings: no secrets were specified in the settings file
[2017-01-19 21:00:35,380] pwnage101/INFO/helpers.settings: loaded the following public settings:
{'COURSE_DATA': 'demo_course',
 'COURSE_ID': 'course-v1:Fx+LT001+2015_T3',
 'LOCUST_MAX_WAIT': 1000,
 'LOCUST_MIN_WAIT': 300,
 'LOCUST_TASK_SET': 'LmsTest',
 'MODULE_RENDER_MODIFIER': 1,
 'PROCTORED_EXAM_MODIFIER': 1}
[2017-01-19 21:00:35,380] pwnage101/INFO/locust.main: Starting Locust 0.7.5
[2017-01-19 21:00:35,380] pwnage101/INFO/locust.runners: Hatching and swarming 525 clients at the rate 25 clients/s...
[2017-01-19 21:00:40,800] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:00:41,389] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:00:43,542] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:00:53,474] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:00:59,995] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:01:00,962] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:01:04,327] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:01:08,453] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:01:10,131] pwnage101/INFO/locust.runners: All locusts hatched: LmsLocust: 525
[2017-01-19 21:01:10,131] pwnage101/INFO/locust.runners: Resetting stats

[2017-01-19 21:01:11,146] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:01:17,890] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 302, in execute_task
    task(self).run(*args, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 251, in run
    self.on_start()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 21, in on_start
    self.create_attempt()
  File "/home/pwnage101/edx-load-tests/loadtests/lms/proctoring.py", line 27, in create_attempt
    data = {'exam_id': self.course_data.exam_id, 'start_clock': True}
  File "/home/pwnage101/edx-load-tests/loadtests/lms/course_data/__init__.py", line 76, in exam_id
    return random.choice(self['special_exam_ids'])
KeyError: 'special_exam_ids'
[2017-01-19 21:01:47,638] pwnage101/ERROR/stderr: Traceback (most recent call last):
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 267, in create_response
    super(ForumsTasks, self).create_response(thread_id)
  File "/home/pwnage101/edx-load-tests/loadtests/lms/forums.py", line 143, in create_response
    return response.json()['id']
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/pwnage101/edx-load-tests/venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2017-01-19 21:10:35,109] pwnage101/INFO/locust.main: Got SIGTERM signal
[2017-01-19 21:10:35,109] pwnage101/INFO/locust.main: Shutting down (exit code 0), bye.
